version: '3.8'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"   # Map port 8080 trên máy chủ với container
      - "50000:50000" # Port cho Jenkins agents
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # Để Jenkins quản lý Docker trên máy host
    restart: unless-stopped

volumes:
  jenkins_home:
